theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: "bookmarklets/*"
    values:
      layout: "script"
  -
    scope:
      path: "_script/*"
    values:
      layout: "script"
collections:
  scripts:
    output: true
    permalink: /bookmarklets/:path.js
  common:
    output: true
    permalink: /libs/:path.js
liquid:
  error_mode: lax
emptyArray: []
curlyOpen: "{"
curlyClose: "}"
newLine: "\n"
SPACE: " "

