theme: jekyll-theme-minimal
collections:
  scripts:
    output: true
    permalink: /bookmarklets/:path.js
  common:
    output: true
    permalink: /libs/:path.js
liquid:
  error_mode: lax
emptyArray: []
curlyOpen: "{"
curlyClose: "}"
newLine: "\n"
SPACE: " "

