---
---
  //before list generation
{%- capture NL -%}
{%- endcapture -%}
{%- assign counter = -1 -%}
window.RogueBM=window.RogueBM||{};
window.RogueBM.about=window.RogueBM.about||{}; //injector should have already created an obj
window.RogueBM.about.scripts={
  "owner_name":"{{ site.github.owner_name }}",
  "owner_url":"{{ site.github.owner_url }}",
  "build_revision":"{{ site.github.build_revision }}",
  "version":"0.0.5"
}
window.RogueBM.scripts={
 /////////////////////////////////
 //       Pages
 /////////////////////////////////
  {{ NL }}
  {%- for script in site.pages -%}
    {%- assign path = script.url | default: '/' | append: script.path | replace: "//", "/"-%} 
    {%- assign name = script.name | split: "." | first | slugify  -%}
    {%- assign modified_time = script.modified_time | default: script.date -%}
    {%- if script.slug and script.tags and script.title and script.relative_path and script.categories and script.draft -%}
      {%- assign jekyll_type = "collection" -%}
    {%- elsif script.extname and script.basename and script.modified_time -%}
      {%- assign jekyll_type = "static" -%}
    {%- elsif script.url and script.dir -%}
      {%- assign jekyll_type = "page" -%}
    {%- else -%}
      {%- assign jekyll_type = "unidentified" -%}
    {%- endif -%}  
        
    {%- assign check = path | split: "/bookmarklets/"  -%}
    
      {%- if check[0] == '' -%}
       "{{ name }}":{
          "name":"{{ name }}",
          "path":"{{ path }}",
          "index":{% increment counter %},
          "modified_time":"{{ modified_time }}",
          "edit":"https://github.com/ktsuttlemyre/RogueBookmarklets/edit/master{{ path | url_escape }}",
          //"src":"https://ktsuttlemyre.github.io/RogueBookmarklets{{ script.path | url_escape }}",
          "jekyll_type":"{{ jekyll_type }}",
              {% for entry in script -%}
                {%- if "next previous output content excerpt |" contains entry[0] -%} //extname url title basename dir | modified_time path name
                  {%- continue -%}
                {%- endif -%}
                {%- if entry.first -%}
                  {{ entry[0] | jsonify }}:{{ entry[1] | jsonify }},
                {%- else -%}
                  {{ entry | jsonify }}:{{ script[entry] | jsonify }},
                {%- endif %}
              {% endfor %}
        },
      {% endif %}
  {%- endfor -%}
  {{ NL }}
 /////////////////////////////////
 //       Collections
 /////////////////////////////////
   {{ NL }}
  {%- for coll in site.collections -%}
    {%- if coll.label == "scripts" -%}
    {%- for script in coll.docs -%}
    {%- assign name = script.url | split: "/" | last | split: "."| first | downcase -%}
     "{{ name | default: script.title }}":{
        "name":"{{ name | default: script.title  }}",
        "path":"{{ script.url }}",
        "index":{% increment counter %},
        "modified_time":"{{ script.modified_time | default: script.date }}",
        "edit":"https://github.com/ktsuttlemyre/RogueBookmarklets/edit/master/{{ script.relative_path | url_escape }}",
        //"src":"https://ktsuttlemyre.github.io/RogueBookmarklets{{ doc.url | url_escape }}",
        "jekyll_type":"collection",
          {% for entry in script %}
            {%- if "next previous output content excerpt |" contains entry -%}
              {%- continue -%}
            {%- endif -%}
            "{{ entry }}":{{ script[entry] | jsonify }},
          {% endfor %}
      },
    {%- endfor -%}
    {%- endif -%}
  {%- endfor -%}
 {{ NL }}
 /////////////////////////////////
 //       Static
 /////////////////////////////////
  {{ NL }}
  {%- for script in site.static_files -%}
  {%- assign path = script.path | split: "/" -%}
  {%- if path[1] contains 'bookmarklets' -%}
   "{{ script.basename | escape }}":{
      "name":"{{ script.basename }}",
      "path":"{{ script.path }}",
      "index":{% increment counter %},
      "modified_time":"{{ script.modified_time | default: script.date }}",
      "edit":"https://github.com/ktsuttlemyre/RogueBookmarklets/edit/master{{ script.path | url_escape }}",
      //"src":"https://ktsuttlemyre.github.io/RogueBookmarklets{{ script.path | url_escape }}",
      "jekyll_type":"static",
          {% for entry in script %}
            {%- if "next previous output content excerpt |" contains entry -%}
              {%- continue -%}
            {%- endif -%}
            "{{ entry }}":{{ script[entry] | jsonify }},
          {% endfor %}
    },
  {%- endif -%}
  {%- endfor -%}
  {% comment %}
//   //http://7is7.com/software/bookmarklets/translate.html
//   "GoogleunTranslate": "(function(){l=location.href;if(l.indexOf('translate')){location.href=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};})()",
//   "Google Translate [Afrikaans]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=af&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=af';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Shqip]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sq&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sq';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [አማርኛ]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=am&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=am';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [العربية]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ar&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ar';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Հայերեն]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=hy&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=hy';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Azərbaycan]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=az&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=az';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Euskara]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=eu&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=eu';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Беларуская]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=be&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=be';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [বাংলা]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=bn&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=bn';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Bosanski]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=bs&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=bs';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Български]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=bg&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=bg';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Català]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ca&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ca';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Cebuano]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ceb&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ceb';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Chichewa]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ny&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ny';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [中文(简体)]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=zh-CN&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=zh-CN';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [中文(繁體)]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=zh-TW&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=zh-TW';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Corsu]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=co&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=co';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Hrvatski]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=hr&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=hr';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Česky]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=cs&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=cs';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Dansk]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=da&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=da';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Nederlands]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=nl&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=nl';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [English]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=en&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=en';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Esperanto]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=eo&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=eo';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Eesti]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=et&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=et';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Tagalog]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=tl&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=tl';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Suomi]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=fi&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=fi';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Français]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=fr&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=fr';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Frysk]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=fy&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=fy';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Galego]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=gl&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=gl';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ქართული]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ka&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ka';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Deutsch]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=de&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=de';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Ελληνικά]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=el&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=el';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ગુજરાતી]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=gu&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=gu';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Kreyòl Ayisyen]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ht&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ht';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Hausa]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ha&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ha';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Hawai‘i]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=haw&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=haw';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [עברית]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=iw&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=iw';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [हिन्दी]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=hi&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=hi';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Hmong]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=hmn&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=hmn';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Magyar]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=hu&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=hu';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Íslenska]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=is&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=is';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Igbo]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ig&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ig';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Bahasa Indonesia]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=id&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=id';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Gaeilge]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ga&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ga';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Italiano]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=it&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=it';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [日本語]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ja&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ja';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Basa Jawa]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=jw&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=jw';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ಕನ್ನಡ]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=kn&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=kn';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Қазақ]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=kk&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=kk';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ភាសាខ្មែរ]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=km&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=km';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [한국어]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ko&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ko';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Kurdî]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ku&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ku';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Кыргыз]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ky&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ky';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ລາວ]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=lo&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=lo';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Latina]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=la&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=la';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Latviešu]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=lv&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=lv';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Lietuvių]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=lt&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=lt';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Lëtzebuergesch]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=lb&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=lb';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Македонски]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=mk&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=mk';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Malagasy]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=mg&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=mg';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Bahasa Melayu]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ms&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ms';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [മലയാളം]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ml&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ml';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Malti]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=mt&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=mt';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Te Reo Māori]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=mi&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=mi';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [मराठी]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=mr&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=mr';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Монгол]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=mn&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=mn';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [မြန်မာစာ]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=my&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=my';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [नेपाली]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ne&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ne';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Norsk]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=no&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=no';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [پښتو]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ps&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ps';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [فارسی]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=fa&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=fa';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Polski]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=pl&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=pl';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Português]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=pt&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=pt';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ਪੰਜਾਬੀ]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=pa&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=pa';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Română]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ro&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ro';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Русский]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ru&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ru';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [gagana Sāmoa]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sm&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sm';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Gàidhlig]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=gd&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=gd';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Српски]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sr&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sr';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Sesotho]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=st&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=st';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ChiShona]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sn&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sn';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [سنڌي]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sd&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sd';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [සිංහල]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=si&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=si';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Slovenčina]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sk&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sk';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Slovenščina]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sl&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sl';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Af Soomaali]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=so&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=so';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Español]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=es&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=es';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Basa Sunda]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=su&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=su';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Kiswahili]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sw&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sw';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Svenska]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=sv&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=sv';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [тоҷикӣ]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=tg&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=tg';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [தமிழ்]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ta&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ta';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [తెలుగు]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=te&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=te';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ไทย]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=th&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=th';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Türkçe]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=tr&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=tr';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Українська]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=uk&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=uk';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [اُردو]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=ur&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=ur';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Oʻzbek]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=uz&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=uz';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Tiếng Việt]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=vi&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=vi';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Cymraeg]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=cy&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=cy';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [isiXhosa]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=xh&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=xh';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [ייִדיש]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=yi&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=yi';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [Yorùbá]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=yo&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=yo';wt=window.open(lw);if(window.focus){wt.focus()};})()",
//   "Google Translate [IsiZulu]": "(function(){l=location.href;if(l.indexOf('translate')>=0){l=decodeURIComponent(l.replace(/^.*[&?](trurl|url|u)=/,'').replace(/[&?].*$/,''))};s=document.selection?document.selection.createRange().text:window.getSelection?window.getSelection().toString():document.getSelection?document.getSelection():'';lw=(s=='')?'http://translate.google.com/translate?u='+encodeURIComponent(l)+'&sl=auto&tl=zu&anno=0':'http://translate.google.com/translate_t?text='+s+'&sl=auto&tl=zu';wt=window.open(lw);if(window.focus){wt.focus()};})()",
  {% endcomment %}
   //TODO link bookmarks https://www.squarefree.com/bookmarklets/pagelinks.html
  //https://www.online-tech-tips.com/cool-websites/the-12-best-bookmarklets-every-browser-should-have/
  "bugmenot":"(function() { var url = ('http://www.bugmenot.com/view/' + escape(location.hostname)); w = open(url, 'w', 'location=no,status=yes,menubar=no,scrollbars=yes,resizable=yes,width=500,height=400,modal=yes,dependent=yes'); if (w) { setTimeout('w.focus()', 1000) } else { location = url } })();",
  "instantgram": {"Author":"theus",
  "website":"https://theus.github.io/instantgram/",
  "src":"https://cdn.jsdelivr.net/gh/theus/instantgram/dist/main.js",
  }
//https://github.com/theus/instantgram/blob/gh-pages/dist/main.js
}
RogueBM.scriptCDNs={
  "edit":"https://github.com/ktsuttlemyre/RogueBookmarklets/edit/master/{path}",
  "jsdelivr":"https://cdn.jsdelivr.net/gh/ktsuttlemyre/RogueBookmarklets/{path}",
  "github_raw":"https://raw.githubusercontent.com/ktsuttlemyre/RogueBookmarklets/master/bookmarklets/{path}",
  "github_pages":"https://ktsuttlemyre.github.io/RogueBookmarklets/{path}"
};
   
(function(){
  //encodeURI(RogueBM.stringFormat(RogueBM.scriptEndpoints.edit,RogueBM.scripts['to_qr']))
  var format=function(prefix,suffix){
    return  function(str){
      "use strict";
       // this is the stringFormat function used at stackoverflow
       // orignal https://stackoverflow.com/questions/610406/javascript-equivalent-to-printf-string-format
       var t = typeof arguments[1];
       var args = (t === "object" || (arguments[1].length!=null && t!=="string")) ?
            arguments[1]
           : Array.prototype.slice.call(arguments,1);
       var keys=Object.keys(args)
       for (var i=0,l=keys.length;i<l;i++) {
           str = str.replace(new RegExp(prefix + keys[i] + suffix, "gi"), args[keys[i]]);
       }
       return str;
    };
  }
  RogueBM.stringFormat=format("\\{","\\}")
  RogueBM.stringHandlebarFormat=format("\\{\\{","\\}\\}")
})();
   
   
// //jsonp callback
function readySignal(){
  var callback=window.RogueBM.loaded;
  if (!callback) {//what function to look for
    return setTimeout(readySignal, 10); 
  }
  //call that function we were looking for
  callback('index.js');
}
window.RogueBM.keys=Object.keys(window.RogueBM.scripts);
readySignal()
//window.RogueBM['loaded']('index.js');
